# Generated by Django 3.2.16 on 2022-10-13 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='day_shown',
            field=models.CharField(max_length=50),
        ),
    ]
