# Generated by Django 3.2.16 on 2022-10-20 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='showings',
            name='location',
            field=models.CharField(default='London', max_length=200),
        ),
    ]
